# Source bashrc for login shells
[[ -f ~/.bashrc ]] && source ~/.bashrc

# Omarchy environment
export OMARCHY_PATH="$HOME/.local/share/omarchy"
export PATH="$OMARCHY_PATH/bin:$PATH"

# Auto-start Hyprland on tty1
[[ -z $DISPLAY && $(tty) == /dev/tty1 ]] && exec Hyprland

. "$HOME/.local/share/../bin/env"
